#!/bin/bash
cd /tmp
tar zxvf /tmp/pibang-backgrounds-contrib.tar.gz
if [ /usr/share/backgrounds -d ]; then
	echo "directory exists"
	mv /tmp/backgrounds/* /usr/share/backgrounds/
	rm -r /tmp/backgrounds
else
	echo "creating /usr/share/backgrounds
	mv /tmp/backgrounds /usr/share/
fi
exit 0
